### ISSUE TITLE
Error trying to run via `npm start` on fresh project - `ERR_PACKAGE_PATH_NOT_EXPORTED`

### ISSUE THREAD

**Issue by stv8** [cloud-annotations/docusaurus-openapi#199] opened 2022-07-26 16:18 UTC
I'm on `node 16.16.0` and am encountering an error trying to run Docasaurus after a fresh install.

- I created the app via `npx create-docusaurus-openapi test-docasaurus`
- ran `npm start`
- see error

```shell
[ERROR] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/sidebars/generator' is not defined by "exports" in /Users/sean/Repos/test-docasaurus/node_modules/@docusaurus/plugin-content-docs/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:753:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/sean/Repos/test-docasaurus/node_modules/docusaurus-plugin-openapi/lib/sidebars/index.js:14:21)
```

**Comment by D063520** [comment] 2022-07-26 16:30
same here

**Comment by isaiahdahl** [comment] 2022-07-29 17:34
same here

**Comment by koladev32** [comment] 2022-07-30 10:19
I have the same errors. I tried to switch to a different Node version and `@docusaurus/core` version too. But still having the same issue.

**Comment by bourdakos1** [comment] 2022-07-30 13:59
Can you share your package.json?

**Comment by yzhe819** [comment] 2022-07-31 01:25
I think the problem is caused by an older version of package 0.4.0 on the template, but @docusaurus/core has been updated to 21. I have previously updated the package to the latest 0.6.0 before. https://github.com/cloud-annotations/docusaurus-openapi/pull/195

@bourdakos1 Can you post a new release? It should fix the problem.

**Comment by bourdakos1** [comment] 2022-07-31 01:38
@yzhe819 if you follow the doc here: https://github.com/cloud-annotations/docusaurus-openapi/tree/main/scripts

and make a PR similar to this one: https://github.com/cloud-annotations/docusaurus-openapi/pull/192

it will automatically release a new version when merged

**Comment by fuchien** [comment] 2022-08-02 16:40
same here

**Comment by lerela** [comment] 2022-08-03 07:29
If you need a hack to run locally before a new version is published (please don't deploy your doc that way):

0. `npx create-docusaurus-openapi test-docusaurus`
1. bump `docusaurus-preset-openapi` to 0.6.0 and `@docusaurus/core` to `^2.0.0` in package.json
2. `yarn install && yarn add url`
3. `cd node_modules && grep -rl IconArrow . | xargs sed -i 's/@theme\/IconArrow/@theme\/Icon\/Arrow/g'`
4. `cd .. && yarn start`

**Comment by doublex** [comment] 2022-08-03 09:09
@lerela 
This works!

**Comment by bourdakos1** [comment] 2022-08-04 05:04
v0.6.1 has been released, thanks @yzhe819 🎉 feel free to reopen this issue if the new version doesn’t resolve the error

**Closed by bourdakos1** 2022-08-04 05:04 UTC
