### ISSUE TITLE
Instructions for example fail

### ISSUE THREAD

**Issue by xgp** [cloud-annotations/docusaurus-openapi#166] opened 2022-02-18 21:28 UTC
using 
1. `yarn create docusaurus-openapi my-website`
2. `cd my-website`
3. `yarn start`

```
[garth:my-website (master)]$ yarn start
yarn run v1.22.17
$ docusaurus start
[INFO] Starting the development server...
[ERROR] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/sidebars/generator' is not defined by "exports" in /Users/garth/projects/saascrud/phasetwo-docs/test/my-website/node_modules/@docusaurus/plugin-content-docs/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/garth/projects/saascrud/phasetwo-docs/test/my-website/node_modules/docusaurus-plugin-openapi/lib/sidebars/index.js:14:21)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Note that by default, this uses the following versions.

```
  "dependencies": {
    "@docusaurus/core": "2.0.0-beta.14",
    "@mdx-js/react": "^1.6.21",
    "clsx": "^1.1.1",
    "docusaurus-preset-openapi": "0.4.0",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
```

**Comment by bourdakos1** [comment] 2022-02-18 22:41
Closing as a duplicate of #160

**Closed by bourdakos1** 2022-02-18 22:41 UTC
